class HDZM69Store : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "HoagieTech"; }
	override Name GetItem() { return 'ZM69Rifle'; }
	override string GetIcon() { return "ZM69A0"; }
	override string GetDisplayName() { return "ZM69 Anti-Materiel Rifle"; }
	override int GetBasePrice() { return 690; }
	override string GetFlavorText() { return "For hunting very large, murderous, demonic game."; }
}