class HDCorporateArmourStore : StoreItem
{
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_CORPORATEARMOUR"); }
	override Name GetItem() { return 'CorporateArmour'; }
	override string GetIcon() { return "CARMA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_CORPORATEARMOUR"); }
	override int GetBasePrice() { return 350; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_CORPORATEARMOUR"); }
}