class HDZM69Store : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_ZM69"); }
	override Name GetItem() { return 'ZM69Rifle'; }
	override string GetIcon() { return "ZM69A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_ZM69"); }
	override int GetBasePrice() { return 690; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_ZM69"); }
}