class HD10mmPistol_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_10mmpistol; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_10MMPISTOL"); }
	override Name GetItem() { return 'HD10mmPistol'; }
	override string GetIcon() { return "DLTAA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_10MMPISTOL"); }
	override int GetBasePrice() { return 125; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_10MMPISTOL"); }
}

class HDSigCow_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_sigcow; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_SIGCOW"); }
	override Name GetItem() { return 'HDSigCow'; }
	override string GetIcon() { return "RF10A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_SIGCOW"); }
	override int GetBasePrice() { return 225; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_SIGCOW"); }
}

/*
class HD10mmPistolMag_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_replaceme; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "RadTech Inc."; }
	override Name GetItem() { return 'HD10mMag12'; }
	override string GetIcon() { return "SC15A0"; }
	override string GetDisplayName() { return "10mm Pistol Magazine"; }
	override int GetBasePrice() { return 15; }
	override string GetFlavorText() { return "Two times the power in half as many rounds."; }
}

class HDSigCowMag_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_replaceme; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "RadTech Inc."; }
	override Name GetItem() { return 'HD10mMag25'; }
	override string GetIcon() { return "CM10A0"; }
	override string GetDisplayName() { return "Sig-Cow Magazine"; }
	override int GetBasePrice() { return 50; }
	override string GetFlavorText() { return "You can eat my shorts if you think I'll give a discount on these."; }
}
*/

class HDColt1911_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_colt1911; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_COLT1911"); }
	override Name GetItem() { return 'HDColt1911'; }
	override string GetIcon() { return "M191A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_COLT1911"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_COLT1911"); }
}

class HDCombatShotgun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_combatshotgun; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_COMBATSHOTGUN"); }
	override Name GetItem() { return 'HDCombatShotgun'; }
	override string GetIcon() { return "CTSGA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_COMBATSHOTGUN"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_COMBATSHOTGUN"); }
}

class HDDetectiveSpecialStore : StoreItem
{
	override bool IsEnabled() { return hdm_enable_snubnose; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_SNUBNOSE"); }
	override Name GetItem() { return 'HDSnubNoseRevolver'; }
	override string GetIcon() { return "DTTSA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_SNUBNOSE"); }
	override int GetBasePrice() { return 100; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_SNUBNOSE"); }
}

class HDPlasmaBuster_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_d93; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_D93"); }
	override Name GetItem() { return 'PlasmaBuster'; }
	override string GetIcon() { return "PLASA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_D93"); }
	override int GetBasePrice() { return 300; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_D93"); }
}

class HDFlareGun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_flaregun; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FLAREGUN"); }
	override Name GetItem() { return 'FireBlooper'; }
	override string GetIcon() { return "FLGNA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FLAREGUN"); }
	override int GetBasePrice() { return 50; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FLAREGUN"); }
}

class HDMetalFlareGun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_flaregunmetal; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FLAREGUNMETAL"); }
	override Name GetItem() { return 'MetalFireBlooper'; }
	override string GetIcon() { return "FLMNA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FLAREGUNMETAL"); }
	override int GetBasePrice() { return 80; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FLAREGUNMETAL"); }
}

class HDFP45_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_fp45; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FP45"); }
	override Name GetItem() { return 'HDFP45'; }
	override string GetIcon() { return "LIBPA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FP45"); }
	override int GetBasePrice() { return 90; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FP45"); }
}

class HDFragCannon_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_fragcannon; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FRAGCANNON"); }
	override Name GetItem() { return 'FragCannon'; }
	override string GetIcon() { return "FGCNA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FRAGCANNON"); }
	override int GetBasePrice() { return 250; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FRAGCANNON"); }
}

class HDHackedZMStore : StoreItem
{
	override bool IsEnabled() { return hdm_enable_hzm; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_HZM"); }
	override Name GetItem() { return 'HackedZM66AssaultRifle'; }
	override string GetIcon() { return "RIGLA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_HZM"); }
	override int GetBasePrice() { return 200; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_HZM"); }
}

class HDHushPuppy_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_hushpuppy; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_HUSHPUPPY"); }
	override Name GetItem() { return 'HushPuppyPistol'; }
	override string GetIcon() { return "HUSHA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_HUSHPUPPY"); }
	override int GetBasePrice() { return 100; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_HUSHPUPPY"); }
}

class HDHorseshoePistol_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_juan; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_JUAN"); }
	override Name GetItem() { return 'HDHorseshoePistol'; }
	override string GetIcon() { return "HPISA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_JUAN"); }
	override int GetBasePrice() { return 125; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_JUAN"); }
}

class HDMinerva_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_minerva; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_MINERVA"); }
	override Name GetItem() { return 'MinervaChaingun'; }
	override string GetIcon() { return "MNVNA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_MINERVA"); }
	override int GetBasePrice() { return 320; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_MINERVA"); }
}

class HDDoomedShotgun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_doomhunter; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_DOOMHUNTER"); }
	override Name GetItem() { return 'DoomHunterRandom'; }
	override string GetIcon() { return "HUNTA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_DOOMHUNTER"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_DOOMHUNTER"); }
}

class HDDuckHunter_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_duckhunter; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_DUCKHUNTER"); }
	override Name GetItem() { return 'DuckHunter'; }
	override string GetIcon() { return "DHNTA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_DUCKHUNTER"); }
	override int GetBasePrice() { return 140; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_DUCKHUNTER"); }
}

class HDLessLsthalShotgun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_llhunter; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_LLHUNTER"); }
	override Name GetItem() { return 'LessLethalShotgun'; }
	override string GetIcon() { return "LLSGA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_LLHUNTER"); }
	override int GetBasePrice() { return 130; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_LLHUNTER"); }
}

class HDMoreLethalGun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_xhunter; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_XHUNTER"); }
	override Name GetItem() { return 'ExplosiveShotgun'; }
	override string GetIcon() { return "XLSGA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_XHUNTER"); }
	override int GetBasePrice() { return 180; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_XHUNTER"); }
}

class HDGoldenSARevolver_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_goldensarevolver; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_GOLDENSAREVOLVER"); }
	override Name GetItem() { return 'HDGoldSingleActionRevolver'; }
	override string GetIcon() { return "GSALA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_GOLDENSAREVOLVER"); }
	override int GetBasePrice() { return 180; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_GOLDENSAREVOLVER"); }
}

class HDSingleActionRevolver_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_sarevolver; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_SAREVOLVER"); }
	override Name GetItem() { return 'HDSingleActionRevolver'; }
	override string GetIcon() { return "RSALA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_SAREVOLVER"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_SAREVOLVER"); }
}

class HDObrozz_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_obrozz; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_OBROZZ"); }
	override Name GetItem() { return 'ObrozzPistol'; }
	override string GetIcon() { return "OBRZA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_OBROZZ"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_OBROZZ"); }
}

class HDPhazer_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_phazer; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_PHAZER"); }
	override Name GetItem() { return 'PhazerPistol'; }
	override string GetIcon() { return "PHZPA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_PHAZER"); }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_PHAZER"); }
}

class HDPPSh41_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_ppsh41; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_PPSH41"); }
	override Name GetItem() { return 'HDPPSh41'; }
	override string GetIcon() { return "PS41A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_PPSH41"); }
	override int GetBasePrice() { return 240; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_PPSH41"); }
}

class HDSavage99_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_savage99; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_SAVAGE99"); }
	override Name GetItem() { return 'Savage99SniperRifle'; }
	override string GetIcon() { return "SV39A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_SAVAGE99"); }
	override int GetBasePrice() { return 260; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_SAVAGE99"); }
}

class HDStenMk2_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_stenmk2; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_STENMK2"); }
	override Name GetItem() { return 'HDStenMk2'; }
	override string GetIcon() { return "STNPA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_STENMK2"); }
	override int GetBasePrice() { return 180; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_STENMK2"); }
}

class HDStunGun_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_stungun; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_STUNGUN"); }
	override Name GetItem() { return 'HDStunGun'; }
	override string GetIcon() { return "TASRA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_STUNGUN"); }
	override int GetBasePrice() { return 60; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_STUNGUN"); }
}

class HDTT33_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_tt33; }
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_TT33"); }
	override Name GetItem() { return 'HDTT33Pistol'; }
	override string GetIcon() { return "TKRVA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_TT33"); }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_TT33"); }
}


// ----------------
// AMMUNITION
// ----------------

class HDDynamite_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_dynamite; }
	override int GetType() { return SType_Ammo; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_DYNAMITE"); }
	override Name GetItem() { return 'HDDynamiteAmmo'; }
	override string GetIcon() { return "DYNAA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_DYNAMITE"); }
	override int GetBasePrice() { return 20; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_DYNAMITE"); }
}

class HDMicrocell_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_microcell; }
	override int GetType() { return SType_Ammo; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_MICROCELL"); }
	override Name GetItem() { return 'HDMicroCell'; }
	override string GetIcon() { return "MCLLA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_MICROCELL"); }
	override int GetBasePrice() { return 15; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_MICROCELL"); }
}


// ----------------
// ITEMS
// ----------------

class HD10mmReloader_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_10mmreloader; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_10MMRELOADER"); }
	override Name GetItem() { return 'TenMilAutoReloader'; }
	override string GetIcon() { return "RLD1A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_10MMRELOADER"); }
	override int GetBasePrice() { return 90; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_10MMRELOADER"); }
}

class HD300SavageReloader_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_300savagereloader; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_300SAVAGERELOADER"); }
	override Name GetItem() { return 'SavageAutoReloader'; }
	override string GetIcon() { return "SRLDA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_300SAVAGERELOADER"); }
	override int GetBasePrice() { return 90; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_300SAVAGERELOADER"); }
}

class HD762TokarevReloader_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_762tokarevreloader; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_762TOKAREVRELOADER"); }
	override Name GetItem() { return 'TokarevAutoReloader'; }
	override string GetIcon() { return "RDT7A0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_762TOKAREVRELOADER"); }
	override int GetBasePrice() { return 90; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_762TOKAREVRELOADER"); }
}

class HDCacoPlush_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_cacoplush; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_CACOPLUSH"); }
	override Name GetItem() { return 'CacoPlushDoll'; }
	override string GetIcon() { return "CCPLA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_CACOPLUSH"); }
	override int GetBasePrice() { return 20; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_CACOPLUSH"); }
}

class HDRadiCola_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_radicola; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_RADICOLA"); }
	override Name GetItem() { return 'HDRadiCola'; }
	override string GetIcon() { return "RDCLA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_RADICOLA"); }
	override int GetBasePrice() { return 2; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_RADICOLA"); }
}

class HDAntiGravBoots_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_antigravboots; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_ANTIGRAVBOOTS"); }
	override Name GetItem() { return 'AntiGravBoots'; }
	override string GetIcon() { return "AGRVA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_ANTIGRAVBOOTS"); }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_ANTIGRAVBOOTS"); }
}

class HDAntiRadBoots_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_antiradboots; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_ANTIRADBOOTS"); }
	override Name GetItem() { return 'ProtectiveRadBoots'; }
	override string GetIcon() { return "RDBTA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_ANTIRADBOOTS"); }
	override int GetBasePrice() { return 100; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_ANTIRADBOOTS"); }
}

class HDFieldMedicKit_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_fieldmedickit; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FIELDMEDICKIT"); }
	override Name GetItem() { return 'HDFieldMedicKit'; }
	override string GetIcon() { return "FMKTA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FIELDMEDICKIT"); }
	override int GetBasePrice() { return 10; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FIELDMEDICKIT"); }
}

class HDFirstAidSpray_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_firstaidspray; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_FIRSTAIDSPRAY"); }
	override Name GetItem() { return 'HDFirstAidSpray'; }
	override string GetIcon() { return "FAIDA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_FIRSTAIDSPRAY"); }
	override int GetBasePrice() { return 10; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_FIRSTAIDSPRAY"); }
}

class HDHalfPack_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_halfpack; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_HALFPACK"); }
	override Name GetItem() { return 'WildHalfPack'; }
	override string GetIcon() { return "HPAKA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_HALFPACK"); }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_HALFPACK"); }
}

class HDRadiRadio_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_radiradio; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_RADIRADIO"); }
	override Name GetItem() { return 'HDPocketRadio'; }
	override string GetIcon() { return "RDIOA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_RADIRADIO"); }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_RADIRADIO"); }
}


// ----------------
// ARMOUR
// ----------------

class HDLeatherArmour_Store : StoreItem
{
	override bool IsEnabled() { return hdm_enable_leatherarmour; }
	override int GetType() { return SType_Item; }
	override string GetCategory() { return Stringtable.localize("$MERCH_CAT_LEATHERARMOUR"); }
	override Name GetItem() { return 'HDLeatherArmour'; }
	override string GetIcon() { return "JAKTA0"; }
	override string GetDisplayName() { return Stringtable.localize("$MERCH_TAG_LEATHERARMOUR"); }
	override int GetBasePrice() { return 100; }
	override string GetFlavorText() { return Stringtable.localize("$MERCH_FLAVOR_LEATHERARMOUR"); }
}
